HW-DAO-3
tbondare/DAO3 pull request #1
Opened 2021-01-14 11:19 UTC by tbondare

2021-01-14 11:35 UTC, YuraBondarenko requested changes

2021-01-14 11:35 UTC, YuraBondarenko commented on src/main/java/taxiapp/model/Car.java
> +        this.model = madel;
```suggestion
    Car(String model, Manufacturer manufacturer) {
        this.id = lastAddedId == null ? 1 : ++lastAddedId;
        this.model = model;
```

2021-01-14 11:35 UTC, YuraBondarenko commented on src/main/java/taxiapp/model/Car.java
> +        this.id = lastAddedId == null ? 1 : ++lastAddedId;
ты можешь это не добавлять, так как ты сеттишь id в storage, когда создаешь новый manufacturer
так же и в остальных моделях

2021-01-14 11:35 UTC, YuraBondarenko commented on src/main/java/taxiapp/model/Driver.java
> +        this.id = lastAddedId == null ? 1 : ++lastAddedId;
-

2021-01-14 11:35 UTC, YuraBondarenko commented on src/main/java/taxiapp/model/Manufacturer.java
> +        this.id = lastAddedId == null ? 1 : ++lastAddedId;
-

2021-01-14 11:35 UTC, YuraBondarenko commented on src/main/java/taxiapp/dao/ManufacturerDaoImpl.java
> +        Storage.manufacturers.add(memberManufacture);
```suggestion
        Storage.manufacturers.remove(oldValue);
        Storage.manufacturers.add(manufacturer);
```

2021-01-14 14:29 UTC, YuraBondarenko approved these changes

2021-01-15 07:54 UTC, RomanDubovskyi approved these changes
fix mistakes before merge

2021-01-15 07:54 UTC, RomanDubovskyi commented on pom.xml
> +    </build>
empty line is missing at the end of the file

2021-01-15 07:54 UTC, RomanDubovskyi commented on src/main/java/taxiapp/dao/ManufacturerDaoImpl.java
> +        return Storage.manufacturers.get(Storage.manufacturers.size() - 1);
```suggestion
        return manufacturer;
```
it should be with id already at this point

2021-01-15 07:54 UTC, RomanDubovskyi commented on src/main/java/taxiapp/dao/ManufacturerDaoImpl.java
> +        Manufacturer oldValue = get(manufacturer.getId()).orElseThrow();
```suggestion
        Manufacturer oldValue = get(manufacturer.getId()).get();
```
you can simply use get() if you don't want to throw a specific exception here

2021-01-15 07:54 UTC, RomanDubovskyi commented on src/main/java/taxiapp/dao/ManufacturerDaoImpl.java
> +        return Storage.manufacturers.remove(get(manufacturerId).orElseThrow());
use removeIf method we want to return false if deletion has not been completed, not throw an exception

2021-01-15 07:54 UTC, RomanDubovskyi commented on src/main/java/taxiapp/model/Car.java
> +
car should have a list of drivers

2021-01-15 07:54 UTC, RomanDubovskyi commented on src/main/java/taxiapp/service/ManufacturerService.java
> +    Optional<Manufacturer> get(Long manufacturerId);
```suggestion
   Manufacturer get(Long manufacturerId);
```
on the service layer, we return an object not its optional

2021-01-15 17:15 UTC, merged