Hw 20 connect my sql
tbondare/DAO3 pull request #3
Opened 2021-01-17 00:30 UTC by tbondare

2021-01-17 14:16 UTC, YuraBondarenko requested changes

2021-01-17 14:16 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbcImpl.java
> +        return oldValue;
```suggestion
        String query = "UPDATE manufacturers SET name = ?,"
                + "country = ? WHERE id = ? AND deleted = false;";
        try (Connection connection = ConnectionUtil.getConnection()) {
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, manufacturer.getName());
            statement.setString(2, manufacturer.getCountry());
            statement.setLong(3, manufacturer.getId());
            statement.executeUpdate();           
        } catch (SQLException e) {
            throw new DataProcessingException("Can't update manufacturers", e);
        }
        return manufacture;
```

2021-01-17 14:16 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbcImpl.java
> +            }
exucuteUpdate возвращает количество измененных строк
```suggestion
            return statement.executeUpdate() > 0;
```

2021-01-17 14:16 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbcImpl.java
> +}
здесь можно без блока try

2021-01-17 15:06 UTC, YuraBondarenko approved these changes

2021-01-18 10:34 UTC, merged

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/dao/CarDao.java
> +
redundant empty line

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/dao/CarDaoImpl.java
> +
same

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/dao/CarDaoImpl.java
> +        return Storage.cars.get(Storage.cars.size() - 1);
see previous review on the methods of this class

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/dao/DriverDao.java
> +
same

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/dao/DriverDaoImpl.java
> +        return Storage.drivers.get(Storage.drivers.size() - 1);
same comments as for CarDaoImpl

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbc.java
> +
it is redundant to create the separate DaoJdbc interface
you should already have ManufacturerDao interface

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbcImpl.java
> +
redundant empty line

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/ManufacturerDaoJdbcImpl.java
> +                    .prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
in all methods - open statements in try with resources - see checklist

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/model/Car.java
> +    }
this should be removed

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/service/CarService.java
> +
redundant empty line

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/service/CarService.java
> +    Optional<Car> get(Long id);
`Car`, not `Optional<Car>` - in all services

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/service/CarServiceImpl.java
> +    CarDao carDao;
comments on this were added in the previous review

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/service/ManufacturerServiceJdbcImpl.java
> +public class ManufacturerServiceJdbcImpl implements ManufacturerService {
we should not create a separate service for working with jdbc

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/java/taxiapp/util/ConnectionUtil.java
> +
redundant empty line

2021-01-18 20:45 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                                        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);
add empty line