HW-21 DAO-6
tbondare/DAO3 pull request #6
Opened 2021-01-18 16:26 UTC by tbondare

2021-01-18 18:33 UTC, YuraBondarenko requested changes

2021-01-18 18:33 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            createRelations(car.getDriverList(), car.getId(), connection);
it's unnecessary here because you create car with empty drivers list

2021-01-18 18:33 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            PreparedStatement statement = connection.prepareStatement(query);
add it also to try-with-resources in all methods

2021-01-18 18:33 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +        String manufacturerCountry = resultSet.getString("m.country");
use everywhere resultSet.getObject()

2021-01-18 18:33 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +        }
открывать два conection(один в другом) плохая практика, попробуй вынести это в отдельный метод и сетить лист драйверов отдельно
ниже навел пример

2021-01-18 18:33 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +    }
```suggestion
    public List<Car> getAll() {
        String query = "SELECT c.car_id, c.model, m.id, m.name, m.country "
                + "FROM cars c "
                + "INNER JOIN manufacturers m ON c.manufacturer_id = m.id "
                + "WHERE m.deleted = false AND c.deleted = false;";
        List<Car> carList = new ArrayList<>();
        try (Connection connection = ConnectionUtil.getConnection()) {
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                carList.add(parseResultSetAndQueryDrivers(resultSet, connection));
            }
        } catch (SQLException e) {
            throw new DataProcessingException("Can't get all cars", e);
        }
          for (Car car : carList) {
            car.setDrivers(getDrivers(car.getId()));
        }
        return carList;
    }
```

2021-01-18 18:42 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +        }
а этот метод соответственно возвращает машин без драйверов

2021-01-19 10:38 UTC, YuraBondarenko requested changes

2021-01-19 10:38 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            car = parseCarResultSet(resultSet);
```suggestion
            if (resultSet.next()) {
            car = parseCarResultSet(resultSet);
            }
    ```

2021-01-19 10:38 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            createRelations(car.getDriverList(), car.getId(), connection);
вынеси это за блок try, тк здесь ты создаешь connection in connection

2021-01-19 10:38 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            deleteRelations(id);
при удалении машини не надо удалять связи

2021-01-19 10:38 UTC, YuraBondarenko commented on src/main/java/taxiapp/jdbc/DriverDaoImpl.java
> +                    .prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
в остальных методах тоже занеси preparedStatement в try-with-resources

2021-01-19 11:18 UTC, YuraBondarenko approved these changes

2021-01-19 15:02 UTC, KseniiaMakarova requested changes
overall good job!

2021-01-19 15:02 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +    private List<Driver> queryDrivers(Long carId) {
```suggestion
    private List<Driver> getDriversByCarId(Long carId) {
```

2021-01-19 15:02 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +                + "AND r.deleted = false AND d.deleted = false;";
```suggestion
                + "AND d.deleted = false;";
```

2021-01-19 15:02 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +        String query = "UPDATE relations SET deleted = true WHERE car_id = ? AND deleted = false;";
```suggestion
        String query = "DELETE FROM relations WHERE car_id = ?;";
```

2021-01-19 15:02 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            for (taxiapp.model.Driver driver : driverList) {
```suggestion
            for (Driver driver : driverList) {
```

2021-01-19 15:02 UTC, KseniiaMakarova commented on src/main/java/taxiapp/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't delete relations", e);
```suggestion
            throw new DataProcessingException("Can't create relations", e);
```

2021-01-19 15:19 UTC, tbondare commented on src/main/java/taxiapp/Main.java
> +            statementDelete = connection.prepareStatement(queryDeleteManufacturers);
Чего-то ошибка вылетает, если сначала мануфактурерс удалить
Cannot delete or update a parent row: a foreign key constraint fails (`taxi_schema`.`cars`, CONSTRAINT `car_manufacturer_fk` FOREIGN KEY (`manufacturer_id`) REFERENCES `manufacturers` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)

2021-01-19 16:00 UTC, KseniiaMakarova commented
we will need to resolve conflict before we merge

2021-01-20 11:29 UTC, merged