HW-23 DAO-8
tbondare/DAO3 pull request #9
Opened 2021-01-21 11:05 UTC by tbondare

2021-01-21 11:28 UTC, oroboro-cpu requested changes

2021-01-21 11:28 UTC, oroboro-cpu commented on src/main/webapp/web.xml
> +        <url-pattern>/drivers/display</url-pattern>
Don’t use plural for package names.
```suggestion
        <url-pattern>/driver/display</url-pattern>
```

2021-01-21 11:28 UTC, oroboro-cpu commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturers/create</url-pattern>
Same here
```suggestion
        <url-pattern>/manufacturer/create</url-pattern>
```

2021-01-21 11:28 UTC, oroboro-cpu commented on src/main/webapp/web.xml
> +        <url-pattern>/cars/addDriver</url-pattern>
```suggestion
        <url-pattern>/cars/drivers/add</url-pattern>
```

2021-01-21 11:28 UTC, oroboro-cpu commented on src/main/java/taxiapp/controller/CreateDriverController.java
> +        String repeatLicenseNumber = req.getParameter("number-repeat");
I don't know if it is necessary to make it in this task. We'll implement this in next homework

2021-01-21 11:49 UTC, oroboro-cpu requested changes

2021-01-21 11:49 UTC, oroboro-cpu commented on src/main/webapp/WEB-INF/views/cars/create.jsp
> +    <title>Title</title>
Make Title more informative for all jsp files

2021-01-21 12:03 UTC, oroboro-cpu requested changes

2021-01-21 12:03 UTC, oroboro-cpu commented on src/main/webapp/web.xml
> +        <url-pattern>/car/addDriver</url-pattern>
```suggestion
        <url-pattern>/car/drivers/add</url-pattern>
```

2021-01-21 12:23 UTC, oroboro-cpu approved these changes

2021-01-21 16:51 UTC, KseniiaMakarova requested changes

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/AddDriverToCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/car/driver/add.jsp").forward(req, resp);
```suggestion
        resp.sendRedirect(req.getContextPath() + "/cars/drivers/add");
```
let's use sendRedirect here instead

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/CreateCarsController.java
> +public class CreateCarsController extends HttpServlet {
```suggestion
public class CreateCarController extends HttpServlet {
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/CreateDriverController.java
> +        Driver driver1 = new Driver(name, licenseNumber);
```suggestion
        Driver driver = new Driver(name, licenseNumber);
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/CreateManufacturerController.java
> +        Manufacturer manufacturer1 = new Manufacturer(name, country);
```suggestion
        Manufacturer manufacturer = new Manufacturer(name, country);
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/CreateManufacturerController.java
> +        System.out.println(name + " " + country);
let's remove this line

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/car/driver/add.jsp
> +<form method="post" action="${pageContext.request.contextPath}/car/driver/add">
```suggestion
<form method="post" action="${pageContext.request.contextPath}/cars/drivers/add">
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/driver/create">
```suggestion
<form method="post" action="${pageContext.request.contextPath}/drivers/create">
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +    <a href="${pageContext.request.contextPath}/car/driver/add">Add driver to car </a><br>
```suggestion
    <a href="${pageContext.request.contextPath}/drivers/create">Create driver </a><br>
    <a href="${pageContext.request.contextPath}/drivers">Display drivers </a><br>
    <a href="${pageContext.request.contextPath}/manufacturers/create">Create manufacturer </a><br>
    <a href="${pageContext.request.contextPath}/cars/create">Create car </a><br>
    <a href="${pageContext.request.contextPath}/cars/drivers/add">Add driver to car </a><br>
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/manufacturer/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/manufacturer/create">
```suggestion
<form method="post" action="${pageContext.request.contextPath}/manufacturers/create">
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <load-on-startup>1</load-on-startup>
let's remove this from all the servlets

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/display</url-pattern>
```suggestion
        <url-pattern>/drivers</url-pattern>
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/create</url-pattern>
```suggestion
        <url-pattern>/drivers/create</url-pattern>
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/create</url-pattern>
```suggestion
        <url-pattern>/manufacturers/create</url-pattern>
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/car/create</url-pattern>
```suggestion
        <url-pattern>/cars/create</url-pattern>
```

2021-01-21 16:51 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/car/driver/add</url-pattern>
```suggestion
        <url-pattern>/cars/drivers/add</url-pattern>
```

2021-01-21 20:26 UTC, KseniiaMakarova requested changes

2021-01-21 20:26 UTC, KseniiaMakarova commented on src/main/java/taxiapp/controller/CreateManufacturerController.java
> +        System.out.println(name + " " + country);
remove this line

2021-01-21 20:26 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/manufacturer/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/manufacturer/create">
do you have the controller in web.xml that is mapped to the endpoint `/manufactureR/create`?

2021-01-21 20:26 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/driver/create">
same here, will this work?

2021-01-21 20:26 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/car/driver/add.jsp
> +<form method="post" action="${pageContext.request.contextPath}/car/driver/add">
same

2021-01-21 20:26 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/car/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/car/create">
same

2021-01-22 05:51 UTC, tbondare commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +<form method="post" action="${pageContext.request.contextPath}/driver/create">
Yes, it is work

2021-01-22 08:20 UTC, KseniiaMakarova approved these changes

2021-01-22 17:08 UTC, merged